import BottomBar from "@/components/shadcn/BottomBar";
import Topbar from "@/components/shadcn/TopBar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Taskify",
  description: "Generated by create next app",
  openGraph:{
    images:[{ 
        url: "https://png.pngtree.com/png-vector/20210117/ourmid/pngtree-red-and-pink-gradient-alphabet-letter-t-3d-design-png-image_2761853.jpg",
        width: 800,
        height: 600,
    }]
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Topbar />
      <Suspense>
            {children}
      </Suspense>
      <BottomBar />
      </body>
    </html>
  );
}